parameters:
    tables:
        root:
            film: s_films
            name: s_names
        child:
            film:
                studio: s_films_studio
                other: s_films_other
                dates: s_films_dates
                cast: s_films_cast
                keywords: s_films_keywords
                awards: s_films_awards
                tracks: s_films_tracks
                sites: s_films_sites
                studio: s_films_studio
            name:
                relations: s_names_relations
                awards: s_names_awards
                sites: s_names_sites