services:
  kp.page_scrap:
    class: AppBundle\Service\PageScrapService
    arguments:
      - @doctrine.dbal.default_connection
      - %tables%
      - %site_url%

  kp.cache_structure:
      class: AppBundle\Service\CacheStructureService
      arguments:
        - @doctrine.dbal.default_connection
        - %tables%