services:
  kp.film_page_scrap:
    class: AppBundle\Service\FilmPageScrapService
    arguments: [@doctrine.dbal.default_connection, %site_url%]

  kp.cache_structure:
      class: AppBundle\Service\CacheStructureService
      arguments: [@doctrine.dbal.default_connection]